/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import ClasesData.ClienteData;
import Modelo.Cliente;
import javax.swing.JOptionPane;

/**
 *
 * @author wilgortiz
 */
public class VistaCliente extends javax.swing.JInternalFrame {

    private Cliente c1;
    private final ClienteData vc;

    public VistaCliente() {
        initComponents();
        this.vc = new ClienteData();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textonombreCliente = new javax.swing.JTextField();
        textoapellidoCliente = new javax.swing.JTextField();
        textodomicilioCliente = new javax.swing.JTextField();
        textotelefonoCliente = new javax.swing.JTextField();
        botonModificarCliente = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        botonEliminarCliente = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textoBuscar = new javax.swing.JTextField();
        botonBuscarCliente = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        textoid = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 102));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CLIENTES");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido");

        jLabel4.setText("Domicilio");

        jLabel5.setText("Telefono");

        botonModificarCliente.setText("Modificar Cliente");
        botonModificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarClienteActionPerformed(evt);
            }
        });

        botonSalir.setText("SALIR");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        botonEliminarCliente.setText("Eliminar Cliente");
        botonEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarClienteActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("buscar un cliente por su nombre");

        jLabel7.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 51));
        jLabel7.setText("nombre del cliente");

        botonBuscarCliente.setText("BUSCAR CLIENTE");
        botonBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarClienteActionPerformed(evt);
            }
        });

        jLabel8.setText("id cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel7)
                .addGap(33, 33, 33)
                .addComponent(textoBuscar)
                .addGap(18, 18, 18)
                .addComponent(botonBuscarCliente)
                .addGap(95, 95, 95))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonSalir)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textodomicilioCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(textoapellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(textonombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textoid, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botonModificarCliente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(botonEliminarCliente))
                                    .addComponent(textotelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonSalir)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 13, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(textoid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textonombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textoapellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textodomicilioCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textotelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonModificarCliente)
                    .addComponent(botonEliminarCliente))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarClienteActionPerformed
        vc.eliminarCliente(textotelefonoCliente.getText());

        limpiar();


    }//GEN-LAST:event_botonEliminarClienteActionPerformed

    private void botonBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarClienteActionPerformed

        String nombre = textoBuscar.getText();
        c1 = vc.buscarClientePorNombre(nombre);

        try {
            textoid.setText(String.valueOf(c1.getIdCliente()));
            textonombreCliente.setText(c1.getNombre());
            textoapellidoCliente.setText(c1.getApellido());
            textodomicilioCliente.setText(c1.getDomicilio());
            textotelefonoCliente.setText(c1.getTelefono());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se encontró el cliente. Por favor, ingrese correctamente el nombre.");
        }

        textoid.setEnabled(false);

//        Cliente cliente;
//
//        try {
//            // Buscamos un cliente por su nombre
//            cliente = vc.buscarClientePorNombre(textoidcliente.getText());
//
//            if (cliente != null) {
//                textodomicilioCliente.setText(cliente.getDomicilio());
//                textonombreCliente.setText(cliente.getNombre());
//                textoapellidoCliente.setText(cliente.getApellido());
//                textotelefonoCliente.setText(cliente.getTelefono());
//                // Hay que parsearlo
//                textoid.setText(String.valueOf(cliente.getIdCliente()));
//            } else {
//                JOptionPane.showMessageDialog(null, "No se encontró el cliente. Por favor, ingrese correctamente el nombre.");
//            }
//        } catch (Exception ex) {
//            JOptionPane.showMessageDialog(null, "Error al buscar el cliente: " + ex.getMessage());
//        }
//        Cliente cliente;
//
//// Buscamos un cliente por su nombre
//        cliente = vc.buscarClientePorNombre(textoidcliente.getText());
//
//        if (cliente != null) {
//            textodomicilioCliente.setText(cliente.getDomicilio());
//            textonombreCliente.setText(cliente.getNombre());
//            textoapellidoCliente.setText(cliente.getApellido());
//            textotelefonoCliente.setText(cliente.getTelefono());
//            // Hay que parsearlo
//            textoid.setText(String.valueOf(cliente.getIdCliente()));
//        } else {
//            JOptionPane.showMessageDialog(null, "No se encontró el cliente. Por favor, ingrese correctamente el nombre.");
//        }
//        Cliente cliente;
//
//        //buscamos un cliente por su nombre
//        cliente = vc.buscarClientePorNombre(textoidcliente.getText());
//
//        textodomicilioCliente.setText(cliente.getDomicilio());
//        textonombreCliente.setText(cliente.getNombre());
//        textoapellidoCliente.setText(cliente.getApellido());
//        textotelefonoCliente.setText((cliente.getTelefono()));
//        //hay que parsearlo 
//        textoid.setText(String.valueOf(cliente.getIdCliente()));
//
//        botongregarCliente.setEnabled(false);
//    //    botonEliminarCliente.setEnabled(false);

    }//GEN-LAST:event_botonBuscarClienteActionPerformed

    private void botonModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarClienteActionPerformed
        Cliente c2 = new Cliente(textoapellidoCliente.getText(), textonombreCliente.getText(), textodomicilioCliente.getText(), textotelefonoCliente.getText());
        vc.modificarCliente(c2, c1.getIdCliente());

        limpiar();

// Cliente c1 = new (id, textoDni.getText(), textoApellido.getText(), textoNombre.getText(), LocalDate.parse(textoFecha.getText()), estado);
//        aD.modificarAlumno(a1);

    }//GEN-LAST:event_botonModificarClienteActionPerformed

    public void limpiar() {
        textodomicilioCliente.setText("");
        textonombreCliente.setText("");
        textoapellidoCliente.setText("");
        textotelefonoCliente.setText("");

        textoid.setText("");

    }
    /*    //setear valores del alumno en los textField
        textoNombre.setText(alumno.getNombre());
        textoApellido.setText(alumno.getApellido());
        textoDni.setText(alumno.getDni());
        textoFecha.setText(alumno.getFechaNacimiento().format(DateTimeFormatter.ISO_DATE));
        if (alumno.isEstado()) {

//             checkActivo.setEnabled(true);
            checkActivo.setSelectebotonModificarCliente
            checkInactivo.setSelected(false);
//             checkInactivo.setEnabled(false);
        } else {
            checkActivo.setSelected(false);
            checkInactivo.setSelected(true);
//             checkInactivo.setEnabled(true);
//             checkActivo.setEnabled(false);
        }

        btnInscribir.setEnabled(false);


    }          */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscarCliente;
    private javax.swing.JButton botonEliminarCliente;
    private javax.swing.JButton botonModificarCliente;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField textoBuscar;
    private javax.swing.JTextField textoapellidoCliente;
    private javax.swing.JTextField textodomicilioCliente;
    private javax.swing.JTextField textoid;
    private javax.swing.JTextField textonombreCliente;
    private javax.swing.JTextField textotelefonoCliente;
    // End of variables declaration//GEN-END:variables
}
